// client/src/views/projects/devices.tsx
// React user loves composition api and JSX 😊
import { onMounted } from '@vue/composition-api';
import { useDevice } from '@/agent/device';

const DevicePage = () => {
  const { load, state } = useDevice();
  onMounted(async () => {
    await load();
  });
  return () => (
    <div>
      <h1>设备管理</h1>
      <el-table data={state.deviceList} v-loading={state.isLoading}>
        <el-table-column label="ID" prop="device_id" width="100px" />
        <el-table-column label="名称" prop="device_name" />
        <el-table-column label="可用性">
          {({ row }) => (
            <el-tag type={row.device_status === 1 ? 'success' : 'info'}>
              {row.device_status === 1 ? '可用' : '不可用'}
            </el-tag>
          )}
        </el-table-column>
      </el-table>
    </div>
  );
};

export default DevicePage;

// client/src/views/projects/devices.jsx
/*
<template>
  <div>
    <h1>设备管理</h1>
    <el-table :data="deviceList">
      <el-table-column label="ID" prop="device_id" width="100px"></el-table-column>
      <el-table-column label="名称" prop="device_name"></el-table-column>
      <el-table-column label="可用性">
        <template slot-scope="scope">
          <el-tag :type="scope.row.device_status === 1 ? 'success' : 'info'">{{
            scope.row.device_status === 1 ? '可用' : '不可用'
          }}</el-tag>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { userStore } from '@/store';
import agent from '@/agent';
import { Device } from 'achieve-it-contract';

@Component
export default class Devices extends Vue {
  deviceList: Device[] = [];
  async mounted() {
    const result = await agent.device.getAll();
    this.deviceList = result.device_list;
  }
}
</script>

<style scoped></style>
*/

import { reactive, createComponent } from '@vue/composition-api';

// React users love composition api
export default createComponent({
  setUp() {},
  render() {
    return <div>123</div>;
  },
});
